services:
  node:
    container_name: circle_node
    build: .
    volumes: 
      - .:/usr/src/app
    ports: 
      - "4200:4200"
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGO_DB_CONNECTION: ${MONGO_DB_CONNECTION}
    depends_on:
      - mongo
  mongo:
    container_name: circle_mongo
    image: mongo
    ports:
      - 27017:2707
    volumes:
      - ./data/db:/data/db
