name: Express Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev, main]

jobs:
  test-and-lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npx nx run express-backend:lint
      - run: npx nx test express-backend --parallel --maxParallel=4 --coverage